### ISSUE TITLE
cannot repeat the results

### ISSUE THREAD

**Issue by rozyang** [vanessajurtz/lasagne4bio#6]
The script fails

$ python scripts/seq2bl.py -i data/c000 -o data/c000.bl.nc -m data/pseudosequences.all.X.dat -b data/BLOSUM62.txt
Traceback (most recent call last):
  File "scripts/seq2bl.py", line 193, in <module>
    blosum = read_blosum(blosumfilename)
  File "scripts/seq2bl.py", line 42, in read_blosum
    if l[0] == "A":
TypeError: 'filter' object is not subscriptable

**Comment by vanessajurtz** [comment]
This error occurs when running the code in python-3.0 instead of python-2.7. I updated seq2bl.py to be compatible with python 3 but recommend running the code in this repository on the python version specified in the dependencies.
